research_spots:
  description: >
    Research the city of {city} and find WELL-REVIEWED places across four buckets:
    Bars, Restaurants, Coffee Shops, and Things To Do. Prioritize recent reviews
    and credible sources (local blogs, newspapers, Eater/Infatuation, Google/Maps).
    Return 5 to 8 options per bucket (fewer for small cities), each with:
    - name
    - neighborhood/area
    - 1 to 2 sentence why-it's-good
    - rough price level ($ to $$$)
    - vibe tags (e.g., cozy, natural wine, third-wave, date-night)
    - 1 to 3 source links
    If the user provides preferences (e.g., “no BBQ”), respect them and exclude.
    If you can't find enough options in a bucket, say so and give what you have.
  expected_output: >
    A Markdown section per bucket with a short intro followed by a table:
    | Name | Neighborhood | Why It's Good | Price | Vibe Tags | Sources |
  agent: researcher

compose_guide:
  description: >
    Turn the research into a tight, skimmable city guide. Keep it upbeat and
    practical. Include:
    - A 2 to 3 sentence overview of the city's food/coffee/bar vibe
    - Sections: Bars, Restaurants, Coffee Shops, Things To Do
    - Within each section, pick the top 3 to 5 highlights and explain who they're for
      (date night, group hang, solo laptop, etc.)
    - “Quick Hits” list for extra picks
    - A final “Plan It” box with tips: best areas to stay, peak hours, reservations
  expected_output: >
    A polished Markdown guide with clear headings, concise blurbs, and a quick
    tips box at the end.
  agent: writer